
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy3"
# command to install dependencies
install:
  - pip install pytest
  - pip install pytest-pep8
# command to run tests
script:
  py.test tests --pep8
